# Uncomment to add libraries
# LIBRARIES += ../deps/stlplus/containers

CXXFLAGS += -Wall -Wextra -std=c++17
CXXFLAGS += -ggdb
CXXFLAGS += -I./ -I../include -I../deps/plog/include

include ../deps/makefiles/gcc.mak
